spring:
  application:
    name: Poke Center
  datasource:
    url: jdbc:h2:mem:pokecenter
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
